groups:
  - name: api_metrics
    rules:
      # Request Rate
      - record: api:request_rate:5m
        expr: rate(http_requests_total[5m])

      # Error Rate
      - record: api:error_rate:5m
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])

      # Average Response Time
      - record: api:response_time_avg:5m
        expr: rate(http_response_time_seconds_sum[5m]) / rate(http_response_time_seconds_count[5m])

      # 95th Percentile Response Time
      - record: api:response_time_p95:5m
        expr: histogram_quantile(0.95, rate(http_response_time_seconds_bucket[5m]))

  - name: node_metrics
    rules:
      # CPU Usage
      - record: node:cpu_usage:5m
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

      # Memory Usage
      - record: node:memory_usage:5m
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100

      # Disk Usage
      - record: node:disk_usage:5m
        expr: 100 - ((node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100) 