# BloomFilterCrawlerLab configuration

# Sizing and accuracy
expectedItems: 500000          # anticipated number of URLs per active filter
targetFPR: 0.01                # desired false positive rate (e.g., 1%)

# Rotation policy
rotation:
  hours: 24                    # rotate active filter every N hours
  graceHours: 24               # keep previous filter for this window to avoid false negatives
  maxBitsSetPercent: 75        # optional: early rotate if active filter gets too saturated

# Snapshot persistence
snapshot:
  dir: data/snapshots          # where to store filter snapshots (relative to project root)
  prefix: bf                   # filename prefix for snapshots
  maxToKeep: 14                # how many historical snapshots to retain

# Service mode
service:
  mode: cli                    # cli | rest
  rest:
    host: 127.0.0.1
    port: 18081

# URL normalization rules
normalizer:
  lowerCaseHost: true
  stripDefaultPorts: true
  stripTrailingSlash: true
  dropFragment: true           # remove #fragment
  sortQueryParams: true        # sort query params for stable representation

# Metrics & logging
metrics:
  enabled: true
  logEverySeconds: 60

# Optional seed data
seedData:
  urlsFile: data/samples/urls.txt

# Storage encoding for snapshots
storage:
  format: raw                  # raw | pickle (raw = custom header + bit array)
