version: '3.8'

services:
  app-v1:
    build: ./app
    environment:
      - APP_VERSION=v1
    expose:
      - "8000"

  app-v2:
    build: ./app
    environment:
      - APP_VERSION=v2
    expose:
      - "8000"

  reverse-proxy:
    image: nginx:1.25-alpine
    ports:
      - "8080:80"
    depends_on:
      - app-v1
      - app-v2
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-cache:/var/cache/nginx

volumes:
  nginx-cache:

