version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: cache_redis
    ports:
      - "6379:6379"

  # Redis Cluster for consistent hashing experiments (6-node cluster in one container)
  redis-cluster:
    image: grokzen/redis-cluster:6.2.6
    container_name: cache_redis_cluster
    ports:
      - "7000-7005:7000-7005"

  app1:
    build: .
    container_name: cache_app1
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - redis-cluster
    environment:
      - FLASK_APP=app.py
      - CACHE_BACKEND=cluster  # change to 'cluster' to use Redis Cluster

  app2:
    build: .
    container_name: cache_app2
    ports:
      - "5001:5000"
    depends_on:
      - redis
      - redis-cluster
    environment:
      - FLASK_APP=app.py
      - CACHE_BACKEND=cluster  # change to 'cluster' to use Redis Cluster

  # NGINX LB to round-robin to app1/app2 on :8080
  lb:
    image: nginx:alpine
    container_name: cache_lb
    depends_on:
      - app1
      - app2
    ports:
      - "8080:80"
    volumes:
      - ./configs/lb/nginx.conf:/etc/nginx/nginx.conf:ro